### ISSUE TITLE
When new HTML is added to incoming, I want the transform-parsoid lambda invoked so that (re)mapped content can be stored for access

### ISSUE THREAD

**Issue by killev** [wikimedia/phoenix#19] opened 2020-08-03 16:39 UTC
When new HTML arrives in `incoming/` (raw content store), subscribers of `sns-raw-content-incoming` are notified.  The `transform-parsoid` lambda (see #4) should respond to these events.

**Comment by eevans** [comment] 2020-08-19 20:01
This is a duplicate of #25

**Closed** 2020-08-19 20:01 UTC
Labels: duplicate
